# Generated by Django 5.1.6 on 2025-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_video_dislikes"),
        ("userauths", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="liked_videos",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="liked_by_users", to="core.video"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="saved_videos",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="saved_by_users", to="core.video"
            ),
        ),
    ]
