# Generated by Django 5.1.6 on 2025-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0007_remove_channel_total_views_and_more"),
        ("userauths", "0003_profile_liked_videos_alter_profile_saved_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="subscribe_by_users",
                to="channel.channel",
            ),
        ),
    ]
