# Generated by Django 5.1.6 on 2025-02-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
