# Generated by Django 5.1.6 on 2025-02-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_comment_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
