# Generated by Django 5.1.6 on 2025-02-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
