# Generated by Django 5.1.6 on 2025-02-16 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_video_likes_alter_video_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
