# Generated by Django 5.1.6 on 2025-02-15 20:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0002_channel_verified_alter_channel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_art",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.user_directory_path
            ),
        ),
    ]
