# Generated by Django 5.1.6 on 2025-02-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0003_channel_channel_art"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="feature",
            field=models.BooleanField(default=False),
        ),
    ]
