# Generated by Django 5.1.6 on 2025-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0004_channel_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="feature",
            field=models.BooleanField(default=True),
        ),
    ]
