# Generated by Django 5.1.6 on 2025-02-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_alter_channel_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="bussiness_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="bussiness_location",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="channel",
            name="total_views",
            field=models.IntegerField(default=0),
        ),
    ]
