# Generated by Django 5.1.6 on 2025-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0007_remove_channel_total_views_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel", name="subs", field=models.IntegerField(default=0),
        ),
    ]
